name: Build on Windows

on:
  workflow_dispatch:
  push:
    tags:
      - *

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.9.*
          modules: qtimageformats

      - name: Configure CMake
        shell: pwsh
        run: |
          mkdir cmakebuild && cd cmakebuild && cmake .. -DCMAKE_BUILD_TYPE=Release -G "Ninja"

      - name: Build
        shell: pwsh
        run: |
          cmake --build cmakebuild --config Release

      - name: Run windeployqt
        shell: pwsh
        run: |
          windeployqt Build/imageconvert.exe

      - name: Upload build directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-folder-windows
          path: Build

      - name: Zip the build folder
        if: github.ref_type == 'tag'
        shell: pwsh
        run: |
          Compress-Archive -Path Build\* -DestinationPath imageconvert-windows.zip

      - name: Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: imageconvert-windows.zip
