name: Build on All Platforms

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.9.*
          modules: qtimageformats

      - name: Configure CMake
        shell: pwsh
        run: |
          mkdir cmakebuild && cd cmakebuild
          cmake .. -DCMAKE_BUILD_TYPE=Release -G "Ninja"

      - name: Build
        shell: pwsh
        run: |
          cmake --build cmakebuild --config Release

      - name: Run windeployqt
        shell: pwsh
        run: |
          windeployqt Build/imageconvert.exe

      - name: Upload build directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-folder-windows
          path: Build

  build-macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.9.*
          modules: qtimageformats

      - name: Configure CMake
        run: |
          mkdir cmakebuild && cd cmakebuild
          cmake .. -DCMAKE_BUILD_TYPE=Release -G "Ninja"

      - name: Build
        run: |
          cmake --build cmakebuild --config Release

      - name: macdeployqt
        run: |
          macdeployqt Build/imageconvert.app

      - name: Upload build directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-folder-macos
          path: Build

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y qt6-base-dev qt6-image-formats-plugins qt6-tools-dev cmake ninja-build

      - name: Configure CMake
        run: |
          mkdir cmakebuild && cd cmakebuild
          cmake .. -DCMAKE_BUILD_TYPE=Release -G "Ninja"

      - name: Build
        run: |
          cmake --build cmakebuild --config Release

      - name: Upload build directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-folder-linux
          path: Build
