name: Build on Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.9.*
          modules: qtimageformats

      - name: Configure CMake
        shell: pwsh
        run: |
          mkdir cmakebuild
          cd cmakebuild
          cmake .. -DCMAKE_BUILD_TYPE=Release -G "Ninja"

      - name: Build with Ninja
        shell: pwsh
        run: |
          cd cmakebuild
          ninja

      - name: Run windeployqt
        shell: pwsh
        run: |
          windeployqt Build/imageconvert.exe

      - name: Upload build directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-folder-windows
          path: Build
          name: build-folder-linux
          path: Build
