name: Build on Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.9.*

      - name: Run Qmake
        shell: pwsh
        run: |
          mkdir build; cd build; qmake ../; nmake

      - name: Prepare deployment with windeployqt
        shell: cmd
        run: |
          windeployqt build/Release/imageconvert.exe

      - name: Upload build directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-folder-windows
          path: build/
