name: Build on Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.9.*
          modules: qtimageformats

      - name: Configure CMake
        shell: pwsh
        run: |
          cmake -B cmake_root -S . -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release

      - name: Build
        shell: pwsh
        run: |
          cmake --build cmake_root --config Release

      - name: Run windeployqt
        shell: pwsh
        run: |
          windeployqt cmake_root/Build/imageconvert.exe

      - name: Upload build directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-folder-windows
          path: cmake_root/
