name: Build on Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3.3.0
        with:
          version: 6.6.*

      - name: Setup MSVC environment
        shell: cmd
        run: |
          call "C:/Program Files/Microsoft Visual Studio/2022/BuildTools/VC/Auxiliary/Build/vcvars64.bat"
          echo "##vso[task.prependpath]C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64"

      - name: Run Makefile
        shell: cmd
        run: |
          make all

      - name: Prepare deployment with windeployqt
        shell: cmd
        run: |
          windeployqt build/Release/imageconvert.exe

      - name: Upload build directory as artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-folder-windows
          path: build/
