name: Build on macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.6.*

      - name: Run Qmake and Build
        shell: bash
        run: |
          mkdir build
          cd build
          qmake ../
          make

      - name: Prepare deployment with macdeployqt
        run: |
          macdeployqt build/imageconvert.app -appstore-compliant -dmg

      - name: Upload build directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-folder-macos
          path: build/*.dmg
